name: Installation Check

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

env:
  FORCE_COLOR: "3"

jobs:

  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Clinguin
      run: |
        python -m pip install ./

    - name: Run Clinguin help
      run: |
        clinguin --help


  build_all:
    name: build all ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Clinguin
      run: |
        python -m pip install ./[doc]

    - name: Run Clinguin help
      run: |
        clinguin --help

  tests:
    name: tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Clinguin
      run: |
        python -m pip install ./[test]

    - name: run tests
      run: nox -e test


  lint_flake8:
    name: lint flake8 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Clinguin
      run: |
        python -m pip install ./[lint_flake8]

    - name: run flake8
      run: nox -e lint_flake8

  lint_pylint:
    name: lint pylint on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Clinguin
      run: |
        python -m pip install ./[lint_pylint]
    - name: run pylint
      run: nox -e lint_pylint
